name: Docker Lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: ghe-actions/dockerfile-validator@v1
      with:
        dockerfile: 'Dockerfile'
        lint: 'hadolint'