name: Docker CI 
on: [push]
jobs:
  Dockerfile-Linter:
    runs-on: ubuntu-latest
    steps:
    - name: Docker lint check
      uses: uditgaurav/docker-linter@v1
      env:
        GITHUB_TOKEN: ${{ secrets.CDK_TOKEN }}
        DOCKERFILE: Dockerfile